// Fake property data
const property = {
  id: 3,
  title: "14 Rangitoto Terrace",
  suburb: "Mission Bay",
  city: "Auckland",
  status: "Active",
  listedDays: 4,
  subtitle: "Coastal family home with sweeping harbour views",
  price: "$2,450,000",
  priceNote: "Enquiries over $2.3M",
  beds: 4,
  baths: 3,
  floor: 228,
  land: 612,
  garage: 2,
  year: 2018,
  description:
    "A sun-drenched four bedroom home set across two levels, just a short walk from Mission Bay beach and the village. Open-plan living flows to a north-facing deck, and the upper level opens to a generous balcony with harbour views.",
  shareUrl: "formz.app/p/d8ksv-rangitoto",
  views: 1247,
  shareClicks: 83,
};

const photos = [
  { id: 1, tone: "#c8bfa7", label: "Exterior · Front", hue: 40 },
  { id: 2, tone: "#a4b1a8", label: "Living · Open plan", hue: 140 },
  { id: 3, tone: "#c9b2a4", label: "Kitchen", hue: 20 },
  { id: 4, tone: "#adb5c5", label: "Master bedroom", hue: 220 },
  { id: 5, tone: "#b8a6b0", label: "Bathroom", hue: 320 },
  { id: 6, tone: "#b0b9a4", label: "Deck · North", hue: 100 },
  { id: 7, tone: "#a9b6c0", label: "Harbour view", hue: 200 },
  { id: 8, tone: "#c4b094", label: "Garden", hue: 60 },
];

const documents = [
  {
    id: 1,
    type: "LIM Report",
    label: "LIM Report 2026",
    size: "2.4 MB",
    pages: 38,
    uploaded: "3 days ago",
    downloads: 12,
    tone: "#2d2bff",
  },
  {
    id: 2,
    type: "Title",
    label: "Record of Title — NA124B/556",
    size: "412 KB",
    pages: 4,
    uploaded: "1 week ago",
    downloads: 18,
    tone: "#0f7a4d",
  },
  {
    id: 3,
    type: "Builders Report",
    label: "Pre-purchase inspection",
    size: "6.1 MB",
    pages: 52,
    uploaded: "1 week ago",
    downloads: 7,
    tone: "#b4530a",
  },
];

const leads = [
  {
    id: 1,
    name: "Priya Ramesh",
    initials: "PR",
    email: "priya.r@gmail.com",
    phone: "021 445 918",
    message: "Interested in a private viewing — weekday evenings work best.",
    when: "12 min ago",
    stage: "New",
    hot: true,
    accent: "#2d2bff",
  },
  {
    id: 2,
    name: "Tama Wilson",
    initials: "TW",
    email: "tama.wilson@outlook.com",
    phone: "027 221 334",
    message: "Requesting LIM and builders report. Pre-approved to $2.6M.",
    when: "2 hours ago",
    stage: "Qualified",
    hot: true,
    accent: "#0f7a4d",
  },
  {
    id: 3,
    name: "Hannah Ogilvie",
    initials: "HO",
    email: "h.ogilvie@xtra.co.nz",
    phone: "021 091 772",
    message: "Second viewing last Sunday — talking to partner this week.",
    when: "Yesterday",
    stage: "Following up",
    hot: false,
    accent: "#b4530a",
  },
  {
    id: 4,
    name: "David Chen",
    initials: "DC",
    email: "dchen@proton.me",
    phone: "022 880 441",
    message: "Asked about school zoning and whether pets are allowed.",
    when: "2 days ago",
    stage: "New",
    hot: false,
    accent: "#6b6860",
  },
  {
    id: 5,
    name: "Rebecca Hall",
    initials: "RH",
    email: "becca.hall@me.com",
    phone: "021 557 009",
    message: "Not proceeding — budget came in under. Thanks for the reply.",
    when: "4 days ago",
    stage: "Closed",
    hot: false,
    accent: "#a29e94",
  },
];

Object.assign(window, { property, photos, documents, leads });
